feat(release-tool): restrict who can publish a release

diff --git a/.semaphore/release/release.yml b/.semaphore/release/release.yml
--- a/.semaphore/release/release.yml
+++ b/.semaphore/release/release.yml
@@ -40,6 +40,22 @@ blocks:
           - cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://asia.gcr.io
           - cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin https://us.gcr.io
       jobs:
+        - name: "Check release prerequisites"
+          execution_time_limit:
+            minutes: 10
+          commands:
+            - |
+              if [ ! -z "${SEMAPHORE_GIT_PR_NUMBER}" ]; then
+                echo "This is a PR, cannot publish release from a PR"
+                exit 1
+              fi
+            - |
+              if [ -z "${SEMAPHORE_PIPELINE_PROMOTED_BY}"]; then
+                export CI_USER=${SEMAPHORE_WORKFLOW_TRIGGERED_BY}
+              else
+                export CI_USER=${SEMAPHORE_PIPELINE_PROMOTED_BY}
+              fi
+            - make -C check-release-prereq CI_USER=${CI_USER}
         - name: "Release on Semaphore VM"
           execution_time_limit:
             minutes: 360
